export { MainPage } from './src/main/ets/components/mainpage/MainPage'
export { USBPort } from './src/main/ets/components/mainpage/USBPort'
export { stringToUint8Array,printNote,cutPaper,pushArray } from './src/main/ets/components/mainpage/PrinterInstance'


export { PrinterInstance } from './src/main/ets/components/mainpage/PrinterInstance'
export { BluetoothPort } from './src/main/ets/components/mainpage/BluetoothPort'
